### ISSUE TITLE
Is correct the use of cookie lib?

### ISSUE THREAD

**Issue by jorgecasar** [fabulator/cookie-api-handler#23]
I opened a PR to request ES Modules syntax support and a member of the library notify that maybe this library is using cookie library incorrectly.

https://github.com/jshttp/cookie/issues/87#issuecomment-466049653

**Comment by fabulator** [comment]
Thanks for info. They are partially right. Their parse method won't parse whole set Cookies response. I just use it for part that is same. And same as for serializer. I'm using this library for several projects and for basic usage it is fine. I want to know only key value and I don't care about expire or domain parameters...

**Comment by jorgecasar** [comment]
Thanks, It's I thought. I hope the decide to distribute it as modules for better integration with this library.
